#!/bin/bash
# ==========================================================
# Runs HyPhy (FEL and MEME) on the codon alignment already
# prepared with prepare_hyphy_input_en.py, using the tree
# already generated by IQ-TREE (Phase 4).
#
# FEL: looks for sites under constant positive/purifying
#      selection across the whole tree.
# MEME: looks for sites under EPISODIC positive selection
#       (only on some branches, not all).
#
# IMPORTANT: run from ~/project
#
# Requirements (install once, in its own environment --
# lesson learned with OrthoFinder, avoids the extremely slow
# conda solver problem):
#   conda create -n hyphy_env --solver=classic -c bioconda -c conda-forge hyphy -y
#
# Usage:
#   cd ~/project
#   bash run_hyphy_en.sh OG0000038
# ==========================================================

set -uo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: bash run_hyphy_en.sh OGxxxxxxx"
    exit 1
fi

OG_ID="$1"
HYPHY_ENV="hyphy_env"

ALIGNMENT="05_selection_hyphy/${OG_ID}/${OG_ID}_codon_alignment.fasta"
# Prefer the PRUNED tree (matching the codon alignment exactly)
# if it exists; otherwise fall back to the original IQ-TREE tree.
PRUNED_TREE="05_selection_hyphy/${OG_ID}/${OG_ID}_pruned.treefile"
if [ -f "$PRUNED_TREE" ]; then
    TREE="$PRUNED_TREE"
    echo "Using PRUNED tree (matches codon alignment exactly): $TREE"
else
    TREE=$(find 04_phylogeny/${OG_ID} -name "*.treefile" 2>/dev/null | head -n1)
    echo "WARNING: no pruned tree found, using original tree (may not match alignment taxa): $TREE"
fi

if [ ! -f "$ALIGNMENT" ]; then
    echo "ERROR: cannot find $ALIGNMENT"
    echo "Run first: python3 prepare_hyphy_input_en.py $OG_ID"
    exit 1
fi

if [ -z "$TREE" ] || [ ! -f "$TREE" ]; then
    echo "ERROR: cannot find the .treefile for $OG_ID in 04_phylogeny/"
    exit 1
fi

echo "Alignment: $ALIGNMENT"
echo "Tree: $TREE"

CONDA_BASE=$(conda info --base)
source "$CONDA_BASE/etc/profile.d/conda.sh"
conda activate "$HYPHY_ENV"

OUT_DIR="05_selection_hyphy/${OG_ID}"

echo "=============================================="
echo "Running FEL (constant per-site selection)..."
echo "=============================================="
hyphy fel --alignment "$ALIGNMENT" --tree "$TREE" \
    --output "${OUT_DIR}/${OG_ID}_FEL.json" \
    2>&1 | tee "${OUT_DIR}/${OG_ID}_FEL.log"

echo "=============================================="
echo "Running MEME (episodic per-site selection)..."
echo "=============================================="
hyphy meme --alignment "$ALIGNMENT" --tree "$TREE" \
    --output "${OUT_DIR}/${OG_ID}_MEME.json" \
    2>&1 | tee "${OUT_DIR}/${OG_ID}_MEME.log"

conda deactivate

echo "=============================================="
echo "HyPhy finished for $OG_ID."
echo "Results: ${OUT_DIR}/${OG_ID}_FEL.json and ${OUT_DIR}/${OG_ID}_MEME.json"
echo "=============================================="
